"""Web demo (PRD §3 — the optional demo page).

The product is the SDK. This exists so the gate can be *seen*: paste an
address or URL, watch real Telegraph miners answer, open the receipt.

    python webapp/server.py           # http://127.0.0.1:8402

Every verdict served here is a live screening over x402. There is no
demo mode and no cached inference — if the wallet is empty, the page says
so rather than showing a canned result.
"""

from __future__ import annotations

import asyncio
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from fastapi import FastAPI, Request  # noqa: E402
from fastapi.responses import HTMLResponse, JSONResponse  # noqa: E402
from fastapi.staticfiles import StaticFiles  # noqa: E402
from pydantic import BaseModel  # noqa: E402

from telegraph_guard import Guard, GuardConfig, __version__  # noqa: E402
from telegraph_guard.classify import classify  # noqa: E402
from telegraph_guard.engine import PaymentUnavailable, signer_address  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent

#: Calibrated miner set — see docs. The auto-router prefers a miner that
#: returns identical prose for a clean router and a sanctioned mixer.
MINERS = ["9002", "95822412", "20260828", "5001"]

app = FastAPI(title="TelegraphGuard", docs_url=None, redoc_url=None)

# Product photography generated by scripts/gen_images.py (Gemini image model).
# The page falls back to an inline SVG when the directory is empty.
_img_dir = HERE / "img"
_img_dir.mkdir(exist_ok=True)
app.mount("/img", StaticFiles(directory=_img_dir), name="img")

_cfg = GuardConfig(deadline_ms=30000, miners=MINERS, miners_per_intent=2)
_guard = Guard(_cfg)
_lock = asyncio.Lock()


class ScreenRequest(BaseModel):
    target: str


# --- public-deployment guardrails -------------------------------------------
#
# Each screening spends real USDC from the demo wallet, so a public URL
# needs a per-IP rate limit and a global session cap: an abuser can waste
# at most the cap, not the wallet.

import time as _time

_PER_IP_LIMIT = 8          # screenings per IP per 10 minutes
_PER_IP_WINDOW = 600.0
_GLOBAL_CAP = 300          # screenings per server session (~$9 worst case)
_ip_hits: dict[str, list[float]] = {}
_served = 0


def _rate_check(ip: str) -> str | None:
    global _served
    if _served >= _GLOBAL_CAP:
        return (
            "This shared demo has hit its session budget. Run it yourself in two "
            "minutes: github.com/preethamresearch/telegraph-guard"
        )
    now = _time.monotonic()
    hits = [t for t in _ip_hits.get(ip, []) if now - t < _PER_IP_WINDOW]
    if len(hits) >= _PER_IP_LIMIT:
        return "Rate limit: 8 screenings per 10 minutes — each one spends real testnet USDC."
    hits.append(now)
    _ip_hits[ip] = hits
    _served += 1
    return None


@app.get("/", response_class=HTMLResponse)
async def index() -> str:
    return (HERE / "index.html").read_text(encoding="utf-8")


BASE_SEPOLIA_RPC = "https://sepolia.base.org"
USDC_BASE_SEPOLIA = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"


async def _usdc_balance(addr: str) -> float | None:
    """Live USDC balance of the agent wallet, read straight from Base Sepolia."""
    import httpx

    data = "0x70a08231" + addr[2:].lower().rjust(64, "0")
    try:
        async with httpx.AsyncClient(timeout=8.0) as c:
            r = await c.post(
                BASE_SEPOLIA_RPC,
                json={
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "eth_call",
                    "params": [{"to": USDC_BASE_SEPOLIA, "data": data}, "latest"],
                },
            )
            return int(r.json()["result"], 16) / 1e6
    except Exception:
        return None


@app.get("/api/status")
async def status() -> JSONResponse:
    try:
        addr = signer_address()
    except PaymentUnavailable:
        addr = None
    balance = await _usdc_balance(addr) if addr else None
    try:
        reg = await _guard.registry()
        miners = {i: len(ms) for i, ms in reg.by_intent.items()}
    except Exception as exc:
        return JSONResponse(
            {"ok": False, "error": str(exc), "signer": addr, "usdc": balance}
        )
    return JSONResponse(
        {
            "ok": True,
            "signer": addr,
            "usdc": balance,
            "explorer": f"https://sepolia.basescan.org/address/{addr}" if addr else None,
            "miners": miners,
            "version": __version__,
            "thresholds": {"allow_below": _cfg.allow_below, "block_above": _cfg.block_above},
        }
    )


@app.post("/api/screen")
async def screen(req: ScreenRequest, request: Request) -> JSONResponse:
    ip = request.headers.get("cf-connecting-ip") or (
        request.client.host if request.client else "?"
    )
    limited = _rate_check(ip)
    if limited:
        return JSONResponse({"error": limited}, status_code=429)

    target = (req.target or "").strip()
    if not target:
        return JSONResponse({"error": "no target supplied"}, status_code=400)
    if classify(target) == "unknown":
        return JSONResponse(
            {
                "error": (
                    "Not a recognised target. Give an EVM address (0x + 40 hex), "
                    "a transaction hash (0x + 64 hex), an ENS name, or a URL."
                )
            },
            status_code=400,
        )

    # Screenings are serialised: concurrent x402 authorizations from one
    # signer race at settlement, and a demo page is not worth the flake.
    async with _lock:
        try:
            verdict = await _guard.screen(target, _cfg)
        except PaymentUnavailable as exc:
            return JSONResponse({"error": str(exc)}, status_code=503)
        except Exception as exc:
            return JSONResponse(
                {"error": f"{type(exc).__name__}: {exc}"}, status_code=502
            )

    data = verdict.to_dict()
    data["evidence"] = sum(1 for s in verdict.signals if s.ok and s.signal_hash)
    return JSONResponse(data)


@app.on_event("shutdown")
async def _shutdown() -> None:
    await _guard.aclose()


def main() -> None:
    import uvicorn

    from telegraph_guard.cli import _load_dotenv

    _load_dotenv()
    try:
        print(f"\n  signer  {signer_address()}")
    except PaymentUnavailable:
        print("\n  WARNING: TELEGRAPH_GUARD_KEY not set — screenings will fail.")
    print("  open    http://127.0.0.1:8402\n")
    uvicorn.run(app, host="127.0.0.1", port=8402, log_level="warning")


if __name__ == "__main__":
    main()
